# Generated by Django 3.1.5 on 2021-01-07 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_course_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=8)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=20, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dept', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
