# Generated by Django 3.1.5 on 2021-01-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentTable',
        ),
    ]
