# Generated by Django 3.1.5 on 2021-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_delete_agenttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='employee',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
